apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlyoffice-notification
  template:
    metadata:
      labels:
        app: onlyoffice-notification
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: [ 'sh', '-c', 'timeout 120s sh -c "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done"' ]
      containers:
        - name: onlyoffice-notification
          image: onlyoffice-monday-notification
          ports:
            - containerPort: 3434
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: onlyoffice
                  key: spring.rabbitmq.host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: onlyoffice
                  key: spring.rabbitmq.port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onlyoffice
                  key: spring.rabbitmq.username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onlyoffice
                  key: spring.rabbitmq.password
            - name: TELEGRAM_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-notification
                  key: camel.component.telegram.authToken
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: onlyoffice-notification
                  key: camel.component.telegram.chatId