apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-user
  labels:
    app: onlyoffice-user
    spring-boot: "true"
spec:
  ports:
    - name: service-port
      port: 8080
      protocol: TCP
    - name: hazelcast-port
      port: 5701
      targetPort: 5701
  selector:
    app: onlyoffice-user
  type: ClusterIP