apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-user
  labels:
    app: onlyoffice-user
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: onlyoffice-user
  type: ClusterIP