apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: onlyoffice-monday
build:
  artifacts:
    - image: onlyoffice-monday-gateway
      custom:
        buildCommand: |
          ./mvnw package -pl onlyoffice-monday-gateway -am -DskipTests && \
          ./mvnw jib:dockerBuild -pl onlyoffice-monday-gateway -DskipTests -Djib.to.image=$IMAGE
        dependencies:
          paths:
            - onlyoffice-monday-gateway/src
            - onlyoffice-monday-gateway/pom.xml
            - onlyoffice-monday-configuration/src
            - onlyoffice-monday-configuration/pom.xml
            - onlyoffice-monday-common/src
            - onlyoffice-monday-common/pom.xml
    - image: onlyoffice-monday-tenant
      custom:
        buildCommand: |
          ./mvnw package -pl onlyoffice-monday-tenant -am -DskipTests && \
          ./mvnw jib:dockerBuild -pl onlyoffice-monday-tenant -DskipTests -Djib.to.image=$IMAGE
        dependencies:
          paths:
            - onlyoffice-monday-tenant/src
            - onlyoffice-monday-tenant/pom.xml
            - onlyoffice-monday-configuration/src
            - onlyoffice-monday-configuration/pom.xml
            - onlyoffice-monday-common/src
            - onlyoffice-monday-common/pom.xml
    - image: onlyoffice-monday-user
      custom:
        buildCommand: |
          ./mvnw package -pl onlyoffice-monday-user -am -DskipTests && \
          ./mvnw jib:dockerBuild -pl onlyoffice-monday-user -DskipTests -Djib.to.image=$IMAGE
        dependencies:
          paths:
            - onlyoffice-monday-user/src
            - onlyoffice-monday-user/pom.xml
            - onlyoffice-monday-configuration/src
            - onlyoffice-monday-configuration/pom.xml
            - onlyoffice-monday-common/src
            - onlyoffice-monday-common/pom.xml
manifests:
  rawYaml:
    - k8s/ingress.yml
    - k8s/onlyoffice-configmap.yml
    - k8s/onlyoffice-role.yml
    - k8s/onlyoffice-secret.yml
    - k8s/postgres-configmap.yml
    - k8s/postgres-deployment.yml
    - k8s/postgres-init-script.yml
    - k8s/postgres-pvc.yml
    - k8s/postgres-service.yml
    - k8s/rabbit-deployment.yml
    - k8s/rabbit-service.yml
    - k8s/redis-deployment.yml
    - k8s/redis-service.yml
    - onlyoffice-monday-gateway/k8s/**.yml
    - onlyoffice-monday-tenant/k8s/**.yml
    - onlyoffice-monday-user/k8s/**.yml