apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: onlyoffice-monday
build:
  artifacts:
    - image: onlyoffice-monday-gateway
      jib:
        project: com.onlyoffice:onlyoffice-monday-gateway
    - image: onlyoffice-monday-tenant
      jib:
        project: com.onlyoffice:onlyoffice-monday-tenant
    - image: onlyoffice-monday-user
      jib:
        project: com.onlyoffice:onlyoffice-monday-user
manifests:
  rawYaml:
    - k8s/ingress.yml
    - k8s/hazelcast-role.yml
    - k8s/hazelcast-rolebinding.yml
    - k8s/onlyoffice-configmap.yml
    - k8s/onlyoffice-role.yml
    - k8s/onlyoffice-secret.yml
    - k8s/postgres-configmap.yml
    - k8s/postgres-deployment.yml
    - k8s/postgres-init-script.yml
    - k8s/postgres-pvc.yml
    - k8s/postgres-service.yml
    - k8s/rabbit-deployment.yml
    - k8s/rabbit-service.yml
    - k8s/redis-deployment.yml
    - k8s/redis-service.yml
    - onlyoffice-monday-gateway/k8s/**.yml
    - onlyoffice-monday-tenant/k8s/**.yml
    - onlyoffice-monday-user/k8s/**.yml