management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info,shutdown
  tracing:
    enabled: ${MANAGEMENT_TRACING_ENABLED:false}
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:0.5}
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    shutdown:
      enabled: true
  otlp:
    enabled: ${MANAGEMENT_OTLP_ENABLED:false}
    metrics:
      export:
        enabled: ${MANAGEMENT_OTLP_ENABLED:false}
        url: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
    tracing:
      enabled: ${MANAGEMENT_TRACING_ENABLED:false}
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true