spring:
  data:
    redis:
      database: ${SPRING_DATA_REDIS_DATABASE:0}
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}
        bundle: ${SPRING_DATA_REDIS_SSL_BUNDLE:}
