server:
  origin: ${SERVER_ORIGIN:}
spring:
  config:
    import:
      - "classpath:application-datasource.yml"
      - "classpath:application-monitoring.yml"
      - "classpath:application-rabbit.yml"
      - "classpath:application-redis.yml"
      - "classpath:application-security.yml"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  shutdown: graceful
  threads:
    virtual:
      enabled: true
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
