apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-gateway
  labels:
    app: onlyoffice-gateway
    spring-boot: "true"
spec:
  ports:
    - port: 3030
      targetPort: 3030
  selector:
    app: onlyoffice-gateway
  type: ClusterIP