apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-tenant
  labels:
    app: onlyoffice-tenant
    spring-boot: "true"
spec:
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: onlyoffice-tenant
  type: ClusterIP