apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-tenant
  labels:
    app: onlyoffice-tenant
    spring-boot: "true"
spec:
  ports:
    - name: service-port
      port: 7070
      protocol: TCP
    - name: hazelcast-port
      port: 5701
      targetPort: 5701
  selector:
    app: onlyoffice-tenant
  type: ClusterIP